# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: PullRequest Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up CocoaPods
      run: pod install

    - name: Create Plist directory
      run: mkdir -p DaliyTimeLine/DaliyTimeLine/Plist

    - name: Check if Plist directory exists
      run: ls -la DaliyTimeLine/DaliyTimeLine/Plist

    - name: Decode GoogleService-Info.plist
      run: echo "${{ secrets.GOOGLE_SERVICE_INFO }}" | base64 --decode > ./DaliyTimeLine/DaliyTimeLine/Plist/GoogleService-Info.plist

    - name: Decode Info.plist
      run: echo "${{ secrets.Info_plist }}" | base64 --decode > ./DaliyTimeLine/DaliyTimeLine/Info.plist

    - name: Build Xcode
      run: |
        xcodebuild clean test -workspace DaliyTimeLine.xcworkspace \
        -scheme DaliyTimeLine \
        -destination 'platform=iOS Simulator,name=iPhone 14 Pro,OS=latest'

    
